// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_CLIENT_KEY = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;
export const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_CLIENT_KEY);

if (import.meta.env.DEV) {
  console.info('[Supabase Frontend Config]', {
    hasUrl: Boolean(SUPABASE_URL),
    hasAnonKey: Boolean(SUPABASE_ANON_KEY),
    hasPublishableKey: Boolean(SUPABASE_PUBLISHABLE_KEY),
  });
}

if (!hasSupabaseEnv) {
  console.error(
    '[CivicFix] Supabase environment variables are missing. App will render, but data calls will fail until VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set.'
  );
}

const fetchWithTimeout: typeof fetch = (input, init) => {
  if (init?.signal) return fetch(input, init);

  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => controller.abort(), 10000);

  return fetch(input, { ...init, signal: controller.signal }).finally(() => {
    window.clearTimeout(timeoutId);
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let _client: ReturnType<typeof createClient<Database>> | null = null;

if (!_client) {
  _client = createClient<Database>(
    SUPABASE_URL || 'http://127.0.0.1:54321',
    SUPABASE_CLIENT_KEY || 'missing-supabase-anon-key',
    {
      global: {
        fetch: hasSupabaseEnv ? fetchWithTimeout : fetch,
      },
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    }
  );
}

export const supabase = _client;